export const RUNTIME='https://raw.githubusercontent.com/frittcat/IPTVibe-Runtime/main/runtime/';
export const normalize=s=>String(s||'').normalize('NFD').replace(/\p{M}/gu,'').toLowerCase().replace(/[^\p{L}\p{N}]+/gu,' ').trim();
export function parseVodIndex(text){const rows=[];const seen=new Set();for(const l of text.split('\n')){const c=l.trimEnd().split('\t');if(c.length<7||!['f','s'].includes(c[0]))continue;const key=c[0]+':'+c[1];if(seen.has(key))continue;seen.add(key);rows.push({key,kind:c[0],title:c[1],letter:c[2],year:Number(c[3])||0,id:Number(c[4])||0,poster:c[5],genres:c[6].split(',').filter(Boolean),country:c[7]||'',audio:(c[8]||'').split(',').filter(Boolean),rating:Number(c[9])||0});}return rows;}
export function mergeTitles(base,search,metadata=''){const rows=new Map(base.map(r=>[r.key,r]));const meta=new Map();for(const l of metadata.split('\n')){const c=l.split('\t');if(c.length>=5)meta.set(c[0]+':'+c[1],c);}for(const l of search.split('\n')){const c=l.trimEnd().split('\t');if(c.length<3||!['f','s'].includes(c[1])||!c[0])continue;const key=c[1]+':'+c[0];if(!rows.has(key)){const m=meta.get(key)||[];rows.set(key,{key,kind:c[1],title:c[0],letter:c[2],year:Number(c[3])||0,id:Number(m[2])||0,poster:m[3]||'',genres:(m[4]||'').split(',').filter(Boolean),country:'',audio:[],rating:0});}}return [...rows.values()];}
export function filterCatalog(rows,{scope='f',query='',genre='',year='',country='',audio='',rating=0,kids=[]}={}){const terms=normalize(query).split(' ').filter(Boolean),allowed=new Set(kids.map(x=>(x.series?'s':'f')+':'+x.tmdb));return rows.filter(r=>{if(scope==='kids'){if(!allowed.has(r.kind+':'+r.id))return false;}else if(r.kind!==scope)return false;return terms.every(t=>normalize(r.title).includes(t))&&(!genre||r.genres.includes(genre))&&(!year||String(r.year)===String(year))&&(!country||r.country.split(',').includes(country))&&(!audio||r.audio.includes(audio))&&r.rating>=Number(rating);});}
export function parseLive(text){const channels=[];let row,source;for(const l of text.split('\n')){const m=l.match(/^([a-z]+)\s*:\s*(.*)$/);if(!m)continue;const [,key,value]=m;if(key==='canal'){row={kind:'live',title:value.trim(),category:'Outros',logo:'',sources:[]};channels.push(row);source=null;}else if(row&&key==='categoria')row.category=value.trim();else if(row&&key==='logo')row.logo=value.trim();else if(row&&key==='fonte'){source={url:value.trim()};if(!row.sources.some(x=>x.url===source.url))row.sources.push(source);}else if(source&&['agente','referer','chave'].includes(key))source[key]=value.trim();}return channels;}
export function parseBases(text){const result=new Map();for(const l of text.split('\n')){const m=l.match(/^base:\s*(\d+)\s+(https?:\/\/\S+)/);if(m)result.set(m[1],m[2]);}return result;}
export function expandSource(value,bases){if(/^https?:\/\//.test(value))return value;const m=value.match(/^(\d+):([\w.-]+)$/);if(!m)return null;const b=bases.get(m[1]);if(!b||b.includes('.invalid'))return null;return b+m[2]+(m[2].includes('.')?'':'.mp4');}
export function movieSources(text,title,bases){const l=text.split('\n').find(l=>l.split('\t')[0]===title);if(!l)return [];const result=[];for(const c of l.split('\t').slice(1)){const m=c.match(/^(dub|leg)=(.*)$/);if(!m)continue;for(const v of m[2].split(',')){const url=expandSource(v,bases);if(url&&!result.some(x=>x.url===url))result.push({url,audio:m[1]});}}return result;}
export function seriesShard(text,title){const l=text.split('\n').find(l=>l.split('\t')[0]===title);if(!l)return null;const c=l.split('\t');return /^\d+$/.test(c[2])?Number(c[2]):null;}
export function episodeRows(text,title,bases){const result=[];let active=false;for(const l of text.split('\n')){if(l.startsWith('@')){active=l.slice(1).split('\t')[0]===title;continue;}if(!active)continue;const c=l.trimEnd().split('\t');if(c.length<4||!/^\d+$/.test(c[0])||!/^\d+$/.test(c[1]))continue;const season=Number(c[0]),episode=Number(c[1]);let row=result.find(r=>r.season===season&&r.episode===episode);if(!row){row={season,episode,sources:[]};result.push(row);}const url=expandSource(c[3],bases);if(url&&!row.sources.some(s=>s.url===url))row.sources.push({url,audio:c[2]});}return result.sort((a,b)=>a.season-b.season||a.episode-b.episode);}
export async function contentId(kind,title){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(title));return kind+':'+Array.from(new Uint8Array(b),x=>x.toString(16).padStart(2,'0')).join('');}
