package tv.iptvibe.mobile;
import android.app.*;import android.os.*;import android.view.*;import android.widget.*;import androidx.media3.common.*;import androidx.media3.datasource.*;import androidx.media3.exoplayer.*;import androidx.media3.exoplayer.source.*;import androidx.media3.ui.PlayerView;import org.json.*;import java.util.*;import java.util.concurrent.*;
public class PlayerActivity extends Activity {
 private final Handler ui=new Handler(Looper.getMainLooper());private final ExecutorService work=Executors.newSingleThreadExecutor();private ExoPlayer player;private TextView status;private JSONObject selection,resolved;private JSONArray sources;private String session="";private int index,generation;private long deadline,nextBeat,lastProgress,position=-1;private boolean active,beating;private PlayerView playerView;
 @Override public void onCreate(Bundle state){super.onCreate(state);getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);getWindow().setStatusBarColor(0xff090d10);getWindow().setNavigationBarColor(0xff090d10);LinearLayout root=new LinearLayout(this);root.setOrientation(1);root.setBackgroundColor(0xff090d10);LinearLayout bar=new LinearLayout(this);Button back=new Button(this);back.setText("‹ Voltar");back.setOnClickListener(v->finish());bar.addView(back);status=new TextView(this);status.setTextColor(0xffedf3f0);status.setTextSize(16);status.setPadding(16,16,16,16);bar.addView(status,new LinearLayout.LayoutParams(0,-2,1));Button next=new Button(this);next.setText("Outra fonte");next.setOnClickListener(v->advance());bar.addView(next);root.addView(bar);playerView=new PlayerView(this);root.addView(playerView,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);try{selection=new JSONObject(getIntent().getStringExtra("selection"));index=getIntent().getIntExtra("source",0);}catch(Exception e){finish();}}
 @Override protected void onResume(){super.onResume();if(selection!=null&&!active)authorize();}
 private void authorize(){active=true;int gen=++generation;status.setText("Autorizando reprodução…");work.execute(()->{String id="";try{resolved=AccountApi.call("/resolve",selection);JSONArray all=resolved.getJSONArray("sources");sources=new JSONArray();for(int i=0;i<all.length();i++)if(!all.getJSONObject(i).has("chave"))sources.put(all.getJSONObject(i));if(sources.length()==0)throw new Exception("Sem fonte compatível");String request=UUID.randomUUID().toString();long began=SystemClock.elapsedRealtime();JSONObject grant=AccountApi.call("/sessions/start",new JSONObject().put("requestId",request).put("contentId",resolved.getString("contentId")).put("kind",resolved.getString("kind")).put("title",resolved.getString("title")));id=grant.getString("sessionId");final String granted=id;final long valid=began+Math.min(grant.optLong("leaseSeconds",0),180)*1000;ui.post(()->{if(gen!=generation||!active||isFinishing()){release(granted);return;}session=granted;deadline=valid;nextBeat=SystemClock.elapsedRealtime()+60000;index=Math.min(index,sources.length()-1);openSource();watch(gen);});}catch(Exception e){if(!id.isEmpty())release(id);ui.post(()->{if(gen==generation){active=false;status.setText(message(e));}});}});}
 private String message(Exception e){if(e instanceof AccountApi.Failure){String code=((AccountApi.Failure)e).code;if(code.equals("SCREEN_LIMIT"))return "Limite de telas atingido. Encerre outra reprodução.";if(code.equals("CHANNEL_BLOCKED"))return "Este conteúdo está bloqueado para sua conta.";if(code.equals("ACCOUNT_NOT_ACTIVE"))return "Seu período de acesso terminou ou a conta está inativa.";if(code.equals("LOGIN_REQUIRED"))return "Entre novamente na sua conta.";}return "Não foi possível reproduzir. Confira a conexão e tente novamente.";}
 private void openSource(){if(!active||SystemClock.elapsedRealtime()>=deadline)return;try{if(player!=null)player.release();JSONObject s=sources.getJSONObject(index);Map<String,String> headers=new HashMap<>();if(s.has("agente"))headers.put("User-Agent",s.getString("agente"));if(s.has("referer"))headers.put("Referer",s.getString("referer"));DefaultHttpDataSource.Factory http=new DefaultHttpDataSource.Factory().setConnectTimeoutMs(12000).setReadTimeoutMs(12000).setAllowCrossProtocolRedirects(false).setDefaultRequestProperties(headers);player=new ExoPlayer.Builder(this).setMediaSourceFactory(new DefaultMediaSourceFactory(http)).build();playerView.setPlayer(player);player.addListener(new Player.Listener(){@Override public void onPlayerError(PlaybackException e){advance();}@Override public void onPlaybackStateChanged(int value){if(value==Player.STATE_READY)status.setText(resolved.optString("title")+" · Fonte "+(index+1));}});player.setMediaItem(MediaItem.fromUri(s.getString("url")));player.prepare();player.play();lastProgress=SystemClock.elapsedRealtime();position=-1;status.setText("Abrindo Fonte "+(index+1)+"…");}catch(Exception e){advance();}}
 private void advance(){if(!active){authorize();return;}index++;if(index<sources.length())openSource();else{stop();status.setText("As fontes não responderam. Toque em Outra fonte para tentar novamente.");index=0;}}
 private void watch(int gen){ui.postDelayed(()->{if(!active||generation!=gen||isFinishing())return;long now=SystemClock.elapsedRealtime();if(now>=deadline){stop();status.setText("A sessão expirou. Confira a conexão e tente novamente.");return;}if(player!=null){long current=player.getCurrentPosition();if(current!=position){position=current;lastProgress=now;}else if(player.getPlayWhenReady()&&now-lastProgress>20000)advance();}if(now>=nextBeat&&!beating&&!session.isEmpty()){beating=true;nextBeat=now+10000;String id=session;long began=now;long seconds=Math.max(0,position/1000);work.execute(()->{try{JSONObject grant=AccountApi.call("/sessions/"+id+"/heartbeat",new JSONObject().put("positionSeconds",seconds));ui.post(()->{if(gen==generation&&active){beating=false;deadline=began+Math.min(grant.optLong("leaseSeconds",0),180)*1000;nextBeat=SystemClock.elapsedRealtime()+60000;}});}catch(Exception e){ui.post(()->{if(gen!=generation)return;beating=false;if(e instanceof AccountApi.Failure&&((AccountApi.Failure)e).status<500){stop();status.setText(message(e));}});}});}watch(gen);},1000);}
 private void release(String id){if(id.isEmpty())return;Runnable task=()->{try{AccountApi.call("/sessions/"+id+"/stop",new JSONObject());}catch(Exception ignored){}};if(work.isShutdown())new Thread(task,"IPTVibe-session-stop").start();else work.execute(task);}
 private void stop(){active=false;generation++;beating=false;deadline=0;if(player!=null){player.release();player=null;playerView.setPlayer(null);}String id=session;session="";release(id);}
 @Override protected void onStop(){stop();super.onStop();}
 @Override protected void onDestroy(){ui.removeCallbacksAndMessages(null);stop();work.shutdown();super.onDestroy();}
}
