import {football} from './football.mjs';
import {liveMetadata,resolve} from './media.mjs';
const ACCOUNTS='https://iptvibe-api.iptvibe-admin.workers.dev';
const json=(data,status=200,extra={})=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff',...extra}});
const routes={'/login':['POST','/api/login'],'/register':['POST','/api/register'],'/me':['GET','/api/me'],'/logout':['POST','/api/logout'],'/devices':['GET','/api/devices']};
function accountRoute(path){if(routes[path])return routes[path];if(path==='/resolve')return ['POST','/api/me'];if(/^\/sessions\/[a-f0-9-]{36}\/(heartbeat|stop)$/.test(path))return ['POST','/api'+path];if(path==='/sessions/start')return ['POST','/api'+path];return null;}
async function accounts(request,url,env){const suffix=url.pathname.replace(/^\/api\/account/,'');const route=accountRoute(suffix);if(!route||route[0]!==request.method)return json({code:'NOT_FOUND'},404);if(request.method!=='GET'&&request.headers.get('Origin')!==url.origin)return json({code:'ORIGIN_REQUIRED'},403);
 const token=request.headers.get('Cookie')?.match(/(?:^|;\s*)iptvibe_session=([A-Za-z0-9_-]{43})(?:;|$)/)?.[1];if(!token&&!['/login','/register'].includes(suffix))return json({code:'LOGIN_REQUIRED'},401);
 const headers={'Content-Type':'application/json'};if(token)headers.Authorization='Bearer '+token;let body;
 if(request.method!=='GET'){if(!request.headers.get('Content-Type')?.startsWith('application/json'))return json({code:'JSON_REQUIRED'},415);const reader=request.body?.getReader();let bytes=0;const chunks=[];if(reader)while(true){const {done,value}=await reader.read();if(done)break;bytes+=value.length;if(bytes>8192){await reader.cancel();return json({code:'REQUEST_TOO_LARGE'},413);}chunks.push(value);}body=new Uint8Array(bytes);let offset=0;for(const c of chunks){body.set(c,offset);offset+=c.length;}}
 try{const init={method:suffix==='/resolve'?'GET':request.method,headers,body:suffix==='/resolve'?undefined:body,signal:AbortSignal.timeout(15000)};let upstream;if(env?.ACCOUNTS_SERVICE){const ip=request.headers.get('CF-Connecting-IP');if(ip)headers['CF-Connecting-IP']=ip;upstream=await env.ACCOUNTS_SERVICE.fetch(new Request(ACCOUNTS+route[1],{...init,cf:request.cf}));}else upstream=await fetch(ACCOUNTS+route[1],init);const data=await upstream.json();if(suffix==='/resolve'){if(!upstream.ok)return json(data,upstream.status);if(data.state!=='active'||data.mustChangePassword||(data.validUntil&&data.validUntil<=Date.now()/1000))return json({code:'ACCOUNT_NOT_ACTIVE'},403);try{return json(await resolve(JSON.parse(new TextDecoder().decode(body))));}catch(e){return json({code:['INVALID_FIELDS','NOT_FOUND'].includes(e.message)?e.message:'SOURCE_UNAVAILABLE'},400);}}let extra={};if(suffix==='/login'&&upstream.ok){if(!/^[A-Za-z0-9_-]{43}$/.test(data.token))return json({code:'SERVICE_UNAVAILABLE'},503);extra['Set-Cookie']=`iptvibe_session=${data.token}; Path=/api/account; HttpOnly; Secure; SameSite=Strict; Max-Age=${Math.min(data.expiresIn,2592000)}`;delete data.token;}if(suffix==='/logout')extra['Set-Cookie']='iptvibe_session=; Path=/api/account; HttpOnly; Secure; SameSite=Strict; Max-Age=0';return json(data,upstream.status,extra);}catch{return json({code:'SERVICE_UNAVAILABLE'},503);}}
async function health(){const checkedAt=new Date().toISOString();const services={};await Promise.all([['accounts',ACCOUNTS+'/health'],['updates','https://raw.githubusercontent.com/frittcat/IPTVibe-Runtime/main/updates/latest.json'],['catalog','https://raw.githubusercontent.com/frittcat/IPTVibe-Runtime/main/runtime/vod/busca.txt']].map(async([key,address])=>{try{const r=await fetch(address,{signal:AbortSignal.timeout(6000),cf:{cacheTtl:120,cacheEverything:true}});if(!r.ok)throw Error();if(key==='accounts'){const b=await r.json();services[key]=b.status==='ready'?{state:'good',label:'Operacional · saúde da API'}:{state:'unknown',label:'Configuração pendente'};services.auth=b.passwordLoginReady?{state:'good',label:'Operacional · configuração declarada'}:{state:'unknown',label:'Configuração pendente'};}else if(key==='updates'){const b=await r.json();if(b.schemaVersion!==1||!b.versionCode||!b.sha256)throw Error();services[key]={state:'good',label:'Operacional · manifesto acessível'};}else{const reader=r.body.getReader();const first=await reader.read();await reader.cancel();if(first.done||!first.value.length)throw Error();services[key]={state:'good',label:'Operacional · índice acessível'};}}catch{services[key]={state:'bad',label:'Indisponível nesta verificação'};if(key==='accounts')services.auth={state:'unknown',label:'Não verificado'};}}));return json({checkedAt,services});}
export default {async fetch(request,env){const url=new URL(request.url);if(url.pathname==='/api/football'&&request.method==='GET'){try{return json(await football(url));}catch(e){return json({code:e.message==='INVALID_FIELDS'?'INVALID_FIELDS':'SOURCE_UNAVAILABLE'},e.message==='INVALID_FIELDS'?400:503);}}if(url.pathname==='/api/status'&&request.method==='GET')return health();if(url.pathname==='/api/live'&&request.method==='GET'){try{return json({channels:await liveMetadata()});}catch{return json({code:'SOURCE_UNAVAILABLE'},503);}}if(url.pathname.startsWith('/api/account/'))return accounts(request,url,env);return env.ASSETS.fetch(request);}};
